CREATE TABLE game_inputs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  input_name varchar
);

CREATE TABLE games (
  game_id varchar PRIMARY KEY,
  user_id integer
);

CREATE TABLE game_user (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE game_data (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id varchar,
  user_input integer,
  time_in_miliseconds interval
);




