CREATE TABLE game_inputs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  input_name varchar
);

CREATE TABLE games (
  game_id varchar PRIMARY KEY,
  user_id integer
);

CREATE TABLE game_user (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE game_data (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id varchar,
  user_input integer,
  time_in_milliseconds numeric,
  player_health integer,
  player_x integer,
  player_y integer,
  goat_kills integer,
  squirrel_kills integer
);

CREATE TABLE training_data (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_run int,
  test_mse float,
  center_distance float,
  size_error float,
  overlap_rate float,
  accuracy float,
  combined_score float
);

CREATE TABLE test_run (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE staging_bbox (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  training varchar,
  epoch varchar,
  current_time_start varchar,
  current_time_end varchar,
  mean_squared_error varchar,
  mean_center_dist varchar,
  mean_size_error varchar,
  mean_overlap varchar,
  combined_score varchar,
  acc_all_conditions varchar,
  train_loss varchar,
  val_loss varchar,
  train_acc varchar,
  val_acc varchar,
  current_lr varchar,
  img_size varchar,
  batch_size varchar,
  processed boolean DEFAULT false
);

CREATE TABLE staging_yolo (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  epoch varchar,
  time varchar,
  train_box_loss varchar,
  train_cls_loss varchar,
  train_dfl_loss varchar,
  metrics_precision_B varchar,
  metrics_recall_B varchar,
  metrics_mAP50_B varchar,
  metrics_mAP50_95_B varchar,
  val_box_loss varchar,
  val_cls_loss varchar,
  val_dfl_loss varchar,
  lr_pg0 varchar,
  lr_pg1 varchar,
  lr_pg2 varchar,
  yolo_training_id varchar,
  processed boolean DEFAULT false
);

CREATE TABLE staging_gamedata (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id varchar,
  user_name varchar,
  user_input varchar,
  timestamp varchar,
  player_health integer,
  player_x integer,
  player_y integer,
  goat_kills integer,
  squirrel_kills integer,
  processed boolean DEFAULT false
);

COMMENT ON COLUMN game_inputs.input_name IS 'Possible inputs that will be used in the game_data table - f.e.: left,right,jump,action';

COMMENT ON COLUMN games.game_id IS 'Gameplay ID';

COMMENT ON COLUMN game_user.name IS 'User name that is used when playing a game instance';

COMMENT ON TABLE game_data IS 'Table used for corellating movement data with game instances';

COMMENT ON COLUMN game_data.time_in_milliseconds IS 'Timestamp in Seconds for the duration of a game instance';

COMMENT ON TABLE training_data IS 'Used to store the different settings and training outputs from different test runs';

COMMENT ON TABLE test_run IS 'Table used to save the name of the test runs (referenced in training_data)';

COMMENT ON TABLE staging_bbox IS 'Table for initial upload of bbox trainingsdata to Database. Data will be flagged after edit';

COMMENT ON TABLE staging_yolo IS 'Table for initial upload of YOLO training metrics. Data will be flagged after edit';

COMMENT ON TABLE staging_gamedata IS 'Table for initial upload of gamedata to Database. Data will be flagged after edit';

ALTER TABLE game_data ADD CONSTRAINT game_id_in_game_data FOREIGN KEY (game_id) REFERENCES games (game_id);

ALTER TABLE game_data ADD CONSTRAINT user_input_in_game_data FOREIGN KEY (user_input) REFERENCES game_inputs (id);

ALTER TABLE games ADD CONSTRAINT user_in_game FOREIGN KEY (user_id) REFERENCES game_user (id);

ALTER TABLE training_data ADD CONSTRAINT test_run FOREIGN KEY (test_run) REFERENCES test_run (id);